In [2]:
%pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.2.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

df_titanic = pd.read_csv('titanic_train.csv')
display(df_titanic.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df_titanic['Age_imputed'] = df_titanic.groupby(['Pclass', 'Sex'])['Age'].transform(lambda x: x.fillna(x.median()))
display(df_titanic[['Age', 'Age_imputed', 'Pclass', 'Sex']].head())

    Age  Age_imputed  Pclass     Sex
0  22.0         22.0       3    male
1  38.0         38.0       1  female
2  26.0         26.0       3  female
3  35.0         35.0       1  female
4  35.0         35.0       3    male

In [7]:
df_titanic['Cabin'] = df_titanic['Cabin'].fillna('Unknown')

In [8]:
df_titanic['CabinDeck'] = df_titanic['Cabin'].apply(lambda x: x[0] if pd.notnull(x) and x != 'Unknown' else 'Unknown')

# Show the counts for each CabinDeck
print("Counts for each CabinDeck:")
display(df_titanic['CabinDeck'].value_counts())

Counts for each CabinDeck:

CabinDeck
Unknown    687
C           59
B           47
D           33
E           32
A           15
F           13
G            4
T            1
Name: count, dtype: int64

In [10]:
# Show survival rate by CabinDeck
print("Survival rate by CabinDeck:")
display(df_titanic.groupby('CabinDeck')['Survived'].mean() * 100)

Survival rate by CabinDeck:

CabinDeck
A          46.666667
B          74.468085
C          59.322034
D          75.757576
E          75.000000
F          61.538462
G          50.000000
T           0.000000
Unknown    29.985444
Name: Survived, dtype: float64

In [11]:
df_titanic['is_male'] = df_titanic['Sex'].map({'male': 1, 'female': 0})
display(df_titanic[['Sex', 'is_male']].head())

      Sex  is_male
0    male        1
1  female        0
2  female        0
3  female        0
4    male        1

In [13]:
df_titanic = df_titanic.drop('Name', axis=1)
display(df_titanic.head())

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_imputed,CabinDeck,is_male
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,Unknown,S,22.0,Unknown,1
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,38.0,C,0
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S,26.0,Unknown,0
3,4,1,1,female,35.0,1,0,113803,53.1000,C123,S,35.0,C,0
4,5,0,3,male,35.0,0,0,373450,8.0500,Unknown,S,35.0,Unknown,1

In [14]:
df_titanic = df_titanic.drop('Ticket', axis=1)
display(df_titanic.head())

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Age_imputed,CabinDeck,is_male
0,1,0,3,male,22.0,1,0,7.2500,Unknown,S,22.0,Unknown,1
1,2,1,1,female,38.0,1,0,71.2833,C85,C,38.0,C,0
2,3,1,3,female,26.0,0,0,7.9250,Unknown,S,26.0,Unknown,0
3,4,1,1,female,35.0,1,0,53.1000,C123,S,35.0,C,0
4,5,0,3,male,35.0,0,0,8.0500,Unknown,S,35.0,Unknown,1

In [15]:
# One-hot encode 'Embarked' and 'CabinDeck'
df_titanic = pd.get_dummies(df_titanic, columns=['Embarked', 'CabinDeck'], drop_first=True)

display(df_titanic.head())

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Age_imputed,...,Embarked_Q,Embarked_S,CabinDeck_B,CabinDeck_C,CabinDeck_D,CabinDeck_E,CabinDeck_F,CabinDeck_G,CabinDeck_T,CabinDeck_Unknown
0,1,0,3,male,22.0,1,0,7.2500,Unknown,22.0,...,False,True,False,False,False,False,False,False,False,True
1,2,1,1,female,38.0,1,0,71.2833,C85,38.0,...,False,False,False,True,False,False,False,False,False,False
2,3,1,3,female,26.0,0,0,7.9250,Unknown,26.0,...,False,True,False,False,False,False,False,False,False,True
3,4,1,1,female,35.0,1,0,53.1000,C123,35.0,...,False,True,False,True,False,False,False,False,False,False
4,5,0,3,male,35.0,0,0,8.0500,Unknown,35.0,...,False,True,False,False,False,False,False,False,False,True

In [16]:
# Convert boolean columns to integers (0s and 1s)
boolean_cols = df_titanic.select_dtypes(include='bool').columns
df_titanic[boolean_cols] = df_titanic[boolean_cols].astype(int)

display(df_titanic.head())

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Age_imputed,...,Embarked_Q,Embarked_S,CabinDeck_B,CabinDeck_C,CabinDeck_D,CabinDeck_E,CabinDeck_F,CabinDeck_G,CabinDeck_T,CabinDeck_Unknown
0,1,0,3,male,22.0,1,0,7.2500,Unknown,22.0,...,0,1,0,0,0,0,0,0,0,1
1,2,1,1,female,38.0,1,0,71.2833,C85,38.0,...,0,0,0,1,0,0,0,0,0,0
2,3,1,3,female,26.0,0,0,7.9250,Unknown,26.0,...,0,1,0,0,0,0,0,0,0,1
3,4,1,1,female,35.0,1,0,53.1000,C123,35.0,...,0,1,0,1,0,0,0,0,0,0
4,5,0,3,male,35.0,0,0,8.0500,Unknown,35.0,...,0,1,0,0,0,0,0,0,0,1

In [19]:
# Identify numerical features (excluding the target variable 'Survived' and the index 'PassengerId')
numerical_features = df_titanic.select_dtypes(include=['int64', 'float64']).columns.tolist()
features_to_scale = [feature for feature in numerical_features if feature not in ['Survived', 'PassengerId']]

print("Numerical features to scale:")
display(features_to_scale)

Numerical features to scale:

['Pclass',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'Age_imputed',
 'is_male',
 'Embarked_Q',
 'Embarked_S',
 'CabinDeck_B',
 'CabinDeck_C',
 'CabinDeck_D',
 'CabinDeck_E',
 'CabinDeck_F',
 'CabinDeck_G',
 'CabinDeck_T',
 'CabinDeck_Unknown']

In [20]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the numerical features
df_titanic[features_to_scale] = scaler.fit_transform(df_titanic[features_to_scale])

display(df_titanic.head())

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Age_imputed,...,Embarked_Q,Embarked_S,CabinDeck_B,CabinDeck_C,CabinDeck_D,CabinDeck_E,CabinDeck_F,CabinDeck_G,CabinDeck_T,CabinDeck_Unknown
0,1,0,0.827377,male,-0.530377,0.432793,-0.473674,-0.502445,Unknown,-0.534891,...,-0.307562,0.619306,-0.235981,-0.266296,-0.196116,-0.193009,-0.121681,-0.067153,-0.03352,0.544925
1,2,1,-1.566107,female,0.571831,0.432793,-0.473674,0.786845,C85,0.668392,...,-0.307562,-1.614710,-0.235981,3.755222,-0.196116,-0.193009,-0.121681,-0.067153,-0.03352,-1.835115
2,3,1,0.827377,female,-0.254825,-0.474545,-0.473674,-0.488854,Unknown,-0.234070,...,-0.307562,0.619306,-0.235981,-0.266296,-0.196116,-0.193009,-0.121681,-0.067153,-0.03352,0.544925
3,4,1,-1.566107,female,0.365167,0.432793,-0.473674,0.420730,C123,0.442776,...,-0.307562,0.619306,-0.235981,3.755222,-0.196116,-0.193009,-0.121681,-0.067153,-0.03352,-1.835115
4,5,0,0.827377,male,0.365167,-0.474545,-0.473674,-0.486337,Unknown,0.442776,...,-0.307562,0.619306,-0.235981,-0.266296,-0.196116,-0.193009,-0.121681,-0.067153,-0.03352,0.544925

In [21]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
# Drop the original 'Age' column and 'Sex' since we have 'Age_imputed' and 'is_male'
# Drop 'Cabin' as it was handled by 'CabinDeck'
X = df_titanic.drop(['Survived', 'Age', 'Sex', 'Cabin'], axis=1)
y = df_titanic['Survived']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (712, 17)
X_test shape: (179, 17)
y_train shape: (712,)
y_test shape: (179,)

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [4, 6, 8, 10],
    'min_samples_split': [2, 5, 10]
}

# Initialize the Random Forest Classifier
rf = RandomForestClassifier(random_state=42)

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)

# Perform hyperparameter tuning
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Get the best model
best_rf_model = grid_search.best_estimator_

Best Hyperparameters: {'max_depth': 10, 'min_samples_split': 10, 'n_estimators': 200}

In [23]:
from sklearn.model_selection import cross_val_score

# Evaluate the best model using cross-validation on the entire dataset
cv_scores = cross_val_score(best_rf_model, X, y, cv=5, scoring='accuracy')

print("Cross-validation scores:", cv_scores)
print("Mean cross-validation accuracy:", cv_scores.mean())

Cross-validation scores: [0.76536313 0.80337079 0.86516854 0.80337079 0.85393258]
Mean cross-validation accuracy: 0.8182411650241667